# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, default='')),
                ('short_bio', models.CharField(blank=True, default='', max_length=200)),
                ('profile_img', models.ImageField(blank=True, default='profile_image/default.png', upload_to='profile_image/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('stockname', models.TextField(blank=True, db_column='StockName', null=True)),
                ('stockcompany', models.TextField(blank=True, db_column='StockCompany', null=True)),
                ('stockprice', models.FloatField(blank=True, db_column='StockPrice', null=True)),
                ('stocklink', models.TextField(blank=True, db_column='StockLink', null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
